### ISSUE TITLE
Changed License...

### ISSUE THREAD

**Issue by bdbaddog** [pinetr2e/scons-compiledb#1]
You've licensed your code MIT, but the code you based it on is Licensed Apache.
(Apache is more restrictive).

In general you cannot release code under a less restrictive license than it was initially released.

**Comment by pinetr2e** [comment]
Now changed to Apache license v2.

Thanks for pointing out the potential issue.

**Comment by bdbaddog** [comment]
Additionally I've contacted MongoDB and asked they change the license for this code and the ninja file generation code to MIT.
They're working through their internal processes to see if they are able.

**Comment by pinetr2e** [comment]
That will be great. I will change back to simpler MIT license once MongoDB hopefully changes.

**Comment by bdbaddog** [comment]
Once the license changes we'll likely look at integrating mongoDB's and your code (if you're o.k with that) code into SCons core.

**Comment by pinetr2e** [comment]
Sounds good and I am more than happy if the code can be somehow put into SCons core.
